services:
  vue-app:
    image: node:20 # Используем образ Node.js
    working_dir: /app
    volumes:
      - .:/app # Монтируем текущую директорию
    ports:
      - "8080:8080" # Пробрасываем порт 8080
    command: >
      sh -c "npm install && npm run dev"
