version: '3' 
services: 
  vue-app: 
    build: . 
    ports: 
      - "8080:8080"  # Измените на нужный порт, если необходимо
    environment: 
      - NODE_ENV=development 
    volumes:
      - .:/app  # Синхронизирует текущую директорию с /app в контейнере